server.port=8081

# logging
logging.level.root=info
bpi.logging.interceptor.soap.enabled=false

bpi.soap.api.configure.enabled=false

bpi.web.exceptionhandler.type=default

# multi-environment
bpi.backendadapter.enabled=true

# origins webservice
bpi.rest.origins.basePath=http://localhost:8089
bpi.rest.origins.hello-world-service-endpoint=/hello
bpi.rest.origins.authorization=${ORIGINS_LOSR1}${ORIGINS_LOSR2}${ORIGINS_LOSR3}${ORIGINS_LOSR4}${ORIGINS_LOSR5}

# connection manager
bpi.rest.conn.pool.max-total=150
bpi.rest.conn.pool.default-max-per-route=50
bpi.rest.conn.pool.evict-idle-connection-sleep-time=15000
bpi.rest.conn.pool.max-idle-time=15000
bpi.rest.conn.pool.time-to-live=1800000

# soap ssl
bpi.ssl.soap.enabled=false
bpi.ssl.soap.disableCNCheck=true
bpi.ssl.soap.ciphers.include=.*_EXPORT_.*, .*_EXPORT1024_.*, .*_WITH_DES_.*, .*_WITH_NULL_.*, .*_WITH_AES_.*
bpi.ssl.soap.ciphers.exclude=.*_DH_anon_.*

# rest ssl
bpi.ssl.rest.enabled=false
bpi.ssl.rest.protocol=TLSv1, TLSv1.1, TLSv1.2
bpi.ssl.rest.disableCNCheck=true
bpi.ssl.rest.ciphers=TLS_RSA_WITH_AES_256_CBC_SHA

# security
app.policies=classpath:policies/policy.yml
app.context=KEYSTORE,TRUSTSTORE,MONGO
app.certKeyPart=QDZaVxJDG/8yKWoMAorBTak0Y24Ee8JZjN+MdeilYnNRy9C0LmSt043QBiFRKetwDHpUeEJerQW3ID+SnpUtZDlSjhdNgTzZOo4W2AeIqGaCVuF5rJMZ9WKwepKQthpFaCTJA5faGaWGOTcrhucRnuUANcs3ALYPlr6c3cjgGMFHQKBgA9RbVfNXTpt+SE9E7KMOTffwAGFlTWxf86GbkUtFXlayEyS32+PP8W2dRrR+90zYlu4iY4TLFFgwiS9OzJErvqtBOaFBimKvBlh91WgjoJuUrtVGwQZScRbBvKta+1p1998eTAPnmD/x7eRdDjRj88bs7Sk4s/0nygvPgkPYawvAoGBAMHqHavx8fjPpiHLJ2aTsdd0KSlipYgGpisKncCgDFcSBO9daAeag6L4Ambrg3uQD3SB2WwxC2vQpSUqnM3tXB2HA5rv0Z6eBeLabXKzhNv1OLLHv4QyoN6wcx5lXMztw1k6Ma+bWNTLw2WpzWqn2xV5YnLakZb6lv8H+d2qZ6dpAoGAYakBCoVJvJOFZqo9qSkdL1nLwkQJMzrLSkJlLDAXev5KK/7Tk8KRxNe/MUzSSwGGbU64djNZGPCtnNxJTR+YaZYp0CzOD65+eU/NEZvi4jIyfgWl1GIXPYuqN8GJ2A3jCL//lGnvTWZnKl3EdFVl3IRbgT2SRuhqKVhXw6WLqCU=
app.credsFilePath=src/main/resources/policies/global.secret.enc.properties
app.certStorePath=src/main/resources

BUSINESS.bpi.rest.origins.basePath=http://localhost:8080/mock/businessError
SERVICE.bpi.rest.origins.basePath=http://localhost:8080/mock/serviceError
TIMEOUT.bpi.rest.origins.basePath=http://localhost:8080/mock/timeout
